//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenProgra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_maquillaje
    {
        public int IdMaquillaje { get; set; }
        public string Producto { get; set; }
        public string Marca { get; set; }
        public string Tono { get; set; }
        public int Precio { get; set; }
        public string Lanzamiento { get; set; }
        public string Vencimiento { get; set; }
    }
}
